const std = @import("std");
const pbz = @import("pbz");

pub fn main() !void {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var tree = pbz.MemorySourceTree.init(allocator);
    defer tree.deinit();
    try tree.add("common.proto",
        \\syntax = "proto3";
        \\package demo.reflect;
        \\enum Role { ROLE_UNKNOWN = 0; ROLE_ADMIN = 1; }
        \\message Profile { int64 created_at = 1; bytes avatar = 2; }
    );
    try tree.add("app.proto",
        \\syntax = "proto3";
        \\package demo.reflect;
        \\import "common.proto";
        \\enum Status {
        \\  reserved 5 to 9;
        \\  reserved "STATUS_OLD";
        \\  STATUS_UNKNOWN = 0;
        \\}
        \\message User {
        \\  reserved 100 to 110;
        \\  reserved "legacy";
        \\  int32 id = 1;
        \\  string name = 2;
        \\  repeated string tags = 3;
        \\  map<string, int32> counts = 4;
        \\  Role role = 5;
        \\  Profile profile = 6;
        \\  oneof contact { string email = 7; bool disabled = 8; }
        \\  uint32 quota = 9;
        \\  uint64 total = 10;
        \\  sint32 delta = 11;
        \\  sint64 big_delta = 12;
        \\  fixed32 checksum = 13;
        \\  fixed64 token = 14;
        \\  sfixed32 signed_fixed = 15;
        \\  sfixed64 signed_big_fixed = 16;
        \\  float ratio = 17;
        \\  double score = 18;
        \\  repeated bool flags = 19;
        \\  repeated bytes blobs = 20;
        \\  repeated Role roles = 21;
        \\  repeated uint32 samples = 22;
        \\  repeated sint64 deltas = 23;
        \\  string display_name = 24 [json_name = "shownName"];
        \\  map<string, Role> roles_by_key = 25;
        \\  repeated int32 more_ids = 26;
        \\  repeated int64 more_totals = 27;
        \\  repeated uint64 more_unsigned = 28;
        \\  repeated sint32 more_deltas = 29;
        \\  repeated fixed32 more_fixed32 = 30;
        \\  repeated fixed64 more_fixed64 = 31;
        \\  repeated sfixed32 more_sfixed32 = 32;
        \\  repeated sfixed64 more_sfixed64 = 33;
        \\  repeated float more_floats = 34;
        \\  repeated double more_doubles = 35;
        \\  message Audit { int32 id = 1; }
        \\  enum LocalStatus { LOCAL_UNKNOWN = 0; }
        \\}
        \\service Users {
        \\  option deprecated = true;
        \\  rpc Get (User) returns (User) { option idempotency_level = NO_SIDE_EFFECTS; }
        \\}
    );

    var loaded = try pbz.loadMemory(allocator, &tree, "app.proto");
    defer loaded.deinit();

    const refl = pbz.Reflection.init(allocator, &loaded.registry);
    const user_desc = try refl.message(".demo.reflect.User");
    const app_file = try refl.fileOfMessage(user_desc);
    const profile_desc = try refl.message(".demo.reflect.Profile");
    const role_desc = try refl.enumeration(".demo.reflect.Role");
    const role_file = try refl.fileOfEnum(role_desc);
    try std.testing.expectEqualStrings("app.proto", refl.fileName(app_file));
    try std.testing.expectEqualStrings("demo.reflect", refl.filePackage(app_file));
    try std.testing.expectEqual(pbz.schema.Syntax.proto3, refl.fileSyntax(app_file));
    try std.testing.expectEqual(pbz.schema.Edition.proto3, refl.fileEdition(app_file));
    try std.testing.expectEqualStrings("common.proto", role_file.name);
    try std.testing.expectEqualStrings("User", refl.messageName(user_desc));
    const user_full_name = try refl.messageFullName(user_desc);
    defer allocator.free(user_full_name);
    try std.testing.expectEqualStrings("demo.reflect.User", user_full_name);
    try std.testing.expectEqualStrings("Role", refl.enumName(role_desc));
    const role_full_name = try refl.enumFullName(role_desc);
    defer allocator.free(role_full_name);
    try std.testing.expectEqualStrings("demo.reflect.Role", role_full_name);
    try std.testing.expectEqual(@as(usize, 1), refl.fileImportCount(app_file));
    try std.testing.expectEqualStrings("common.proto", (try refl.fileImportAt(app_file, 0)).path);
    try std.testing.expectError(error.UnknownFile, refl.fileImportAt(app_file, 9));
    try std.testing.expectEqual(@as(usize, 1), refl.fileMessageCount(app_file));
    try std.testing.expect((try refl.fileMessageAt(app_file, 0)) == user_desc);
    try std.testing.expectEqualStrings("User", (try refl.fileMessageAt(app_file, 0)).name);
    try std.testing.expectError(error.UnknownMessage, refl.fileMessageAt(app_file, 9));
    try std.testing.expectEqual(@as(usize, 1), refl.fileEnumCount(app_file));
    try std.testing.expectEqualStrings("Status", (try refl.fileEnumAt(app_file, 0)).name);
    try std.testing.expectError(error.UnknownEnum, refl.fileEnumAt(app_file, 9));
    try std.testing.expectEqual(@as(usize, 1), refl.fileServiceCount(app_file));
    try std.testing.expectEqualStrings("Users", (try refl.fileServiceAt(app_file, 0)).name);
    try std.testing.expectError(error.UnknownService, refl.fileServiceAt(app_file, 9));
    try std.testing.expectEqual(@as(usize, 0), refl.fileExtensionCount(app_file));
    try std.testing.expectError(error.UnknownField, refl.fileExtensionAt(app_file, 0));
    try std.testing.expectEqual(@as(usize, 35), refl.messageFieldCount(user_desc));
    try std.testing.expect((try refl.messageFieldAt(user_desc, 0)) == try refl.fieldByName(user_desc, "id"));
    try std.testing.expectEqualStrings("id", (try refl.messageFieldAt(user_desc, 0)).name);
    try std.testing.expectError(error.UnknownField, refl.messageFieldAt(user_desc, 99));
    try std.testing.expectEqual(@as(usize, 1), refl.messageOneofCount(user_desc));
    try std.testing.expectEqualStrings("contact", (try refl.messageOneofAt(user_desc, 0)).name);
    try std.testing.expectError(error.UnknownField, refl.messageOneofAt(user_desc, 9));
    try std.testing.expectEqual(@as(usize, 1), refl.messageNestedMessageCount(user_desc));
    const audit_desc = try refl.messageNestedMessageAt(user_desc, 0);
    try std.testing.expectEqualStrings("Audit", refl.messageName(audit_desc));
    const audit_full_name = try refl.messageFullName(audit_desc);
    defer allocator.free(audit_full_name);
    try std.testing.expectEqualStrings("demo.reflect.User.Audit", audit_full_name);
    try std.testing.expectError(error.UnknownMessage, refl.messageNestedMessageAt(user_desc, 9));
    try std.testing.expectEqual(@as(usize, 1), refl.messageNestedEnumCount(user_desc));
    const local_status_desc = try refl.messageNestedEnumAt(user_desc, 0);
    try std.testing.expectEqualStrings("LocalStatus", refl.enumName(local_status_desc));
    const local_status_full_name = try refl.enumFullName(local_status_desc);
    defer allocator.free(local_status_full_name);
    try std.testing.expectEqualStrings("demo.reflect.User.LocalStatus", local_status_full_name);
    try std.testing.expectError(error.UnknownEnum, refl.messageNestedEnumAt(user_desc, 9));
    try std.testing.expectEqual(@as(usize, 2), refl.enumValueCount(role_desc));
    const role_unknown_value = try refl.enumValueAt(role_desc, 0);
    try std.testing.expectEqualStrings("ROLE_UNKNOWN", refl.enumValueName(role_unknown_value));
    try std.testing.expectEqual(@as(i32, 0), refl.enumValueNumber(role_unknown_value));
    const role_unknown_full_name = try refl.enumValueFullName(role_desc, role_unknown_value);
    defer allocator.free(role_unknown_full_name);
    try std.testing.expectEqualStrings("demo.reflect.ROLE_UNKNOWN", role_unknown_full_name);
    try std.testing.expectError(error.UnknownEnum, refl.enumValueAt(role_desc, 9));
    try std.testing.expectEqualStrings("ROLE_ADMIN", (try refl.enumValueByNumber(role_desc, 1)).name);
    try std.testing.expectEqual(@as(i32, 0), (try refl.enumValueByName(role_desc, "ROLE_UNKNOWN")).number);
    try std.testing.expectEqualStrings("display_name", (try refl.fieldByJsonName(user_desc, "shownName")).name);
    try std.testing.expectEqualStrings("big_delta", (try refl.fieldByJsonName(user_desc, "bigDelta")).name);
    const explicit_json_name = try refl.fieldJsonName(try refl.fieldByName(user_desc, "display_name"));
    defer allocator.free(explicit_json_name);
    try std.testing.expectEqualStrings("shownName", explicit_json_name);
    const default_json_name = try refl.fieldJsonName(try refl.fieldByName(user_desc, "big_delta"));
    defer allocator.free(default_json_name);
    try std.testing.expectEqualStrings("bigDelta", default_json_name);
    const id_field = try refl.fieldByName(user_desc, "id");
    const tags_field = try refl.fieldByName(user_desc, "tags");
    const role_field = try refl.fieldByName(user_desc, "role");
    const profile_field = try refl.fieldByName(user_desc, "profile");
    const email_field = try refl.fieldByName(user_desc, "email");
    const samples_field = try refl.fieldByName(user_desc, "samples");
    const counts_desc_field = try refl.fieldByName(user_desc, "counts");
    try std.testing.expectEqualStrings("id", refl.fieldName(id_field));
    const id_full_name = try refl.fieldFullName(user_desc, id_field);
    defer allocator.free(id_full_name);
    try std.testing.expectEqualStrings("demo.reflect.User.id", id_full_name);
    try std.testing.expectEqual(@as(pbz.FieldNumber, 1), refl.fieldNumber(id_field));
    try std.testing.expectEqual(pbz.schema.Cardinality.implicit, refl.fieldCardinality(id_field));
    try std.testing.expectEqual(pbz.schema.FieldKind{ .scalar = .int32 }, refl.fieldKind(id_field));
    try std.testing.expectError(error.TypeMismatch, refl.fieldTypeName(id_field));
    try std.testing.expectError(error.TypeMismatch, refl.fieldMessageType(user_desc, id_field));
    try std.testing.expectEqualStrings("Role", try refl.fieldTypeName(role_field));
    try std.testing.expect(role_desc == try refl.fieldEnumType(user_desc, role_field));
    try std.testing.expectEqualStrings("Profile", try refl.fieldTypeName(profile_field));
    try std.testing.expect(profile_desc == try refl.fieldMessageType(user_desc, profile_field));
    try std.testing.expect(!refl.fieldHasOneof(id_field));
    try std.testing.expectError(error.MissingField, refl.fieldOneofName(id_field));
    try std.testing.expect(refl.fieldHasOneof(email_field));
    try std.testing.expectEqualStrings("contact", try refl.fieldOneofName(email_field));
    try std.testing.expect((try refl.fieldContainingOneof(user_desc, email_field)) == try refl.oneofByName(user_desc, "contact"));
    try std.testing.expect(!refl.fieldIsExtension(id_field));
    try std.testing.expectError(error.TypeMismatch, refl.fieldExtendeeName(id_field));
    try std.testing.expect(!(try refl.fieldHasPresence(user_desc, id_field)));
    try std.testing.expect(!(refl.fieldIsRequired(id_field)));
    try std.testing.expect(refl.fieldIsRepeatedLike(tags_field));
    try std.testing.expect(!(refl.fieldIsMap(tags_field)));
    try std.testing.expect(!refl.fieldIsPackable(tags_field));
    try std.testing.expect(refl.fieldIsPackable(samples_field));
    try std.testing.expect(try refl.fieldIsPacked(user_desc, samples_field));
    try std.testing.expect(refl.fieldIsMap(counts_desc_field));
    try std.testing.expectEqual(pbz.schema.ScalarType.string, try refl.fieldMapKeyType(counts_desc_field));
    try std.testing.expectEqual(pbz.schema.FieldKind{ .scalar = .int32 }, try refl.fieldMapValueKind(counts_desc_field));
    try std.testing.expect(refl.fieldIsRepeatedLike(counts_desc_field));
    try std.testing.expect(!refl.fieldIsPackable(counts_desc_field));
    try std.testing.expect(refl.messageReservedName(user_desc, "legacy"));
    try std.testing.expect(refl.messageReservedNumber(user_desc, 100));
    try std.testing.expect(!refl.messageReservedNumber(user_desc, 99));
    const status_desc = try refl.enumeration(".demo.reflect.Status");
    try std.testing.expect(refl.enumReservedName(status_desc, "STATUS_OLD"));
    try std.testing.expect(refl.enumReservedNumber(status_desc, 5));
    try std.testing.expect(!refl.enumReservedNumber(status_desc, 10));
    try std.testing.expectError(error.UnknownField, refl.fieldByJsonName(user_desc, "display_name"));
    const users_service = try refl.service(".demo.reflect.Users");
    try std.testing.expectEqualStrings("Users", refl.serviceName(users_service));
    const users_service_full_name = try refl.serviceFullName(users_service);
    defer allocator.free(users_service_full_name);
    try std.testing.expectEqualStrings("demo.reflect.Users", users_service_full_name);
    try std.testing.expect(users_service == try refl.fileService(app_file, "Users"));
    try std.testing.expectError(error.UnknownService, refl.fileService(app_file, "Missing"));
    const service_file = try refl.fileOfService(users_service);
    try std.testing.expect(service_file == app_file);
    try std.testing.expectEqual(@as(usize, 1), refl.serviceMethodCount(users_service));
    try std.testing.expectEqualStrings("Get", (try refl.serviceMethodAt(users_service, 0)).name);
    try std.testing.expectError(error.UnknownField, refl.serviceMethodAt(users_service, 9));
    const get_method = try refl.methodByName(users_service, "Get");
    try std.testing.expectEqualStrings("Get", refl.methodName(get_method));
    const get_method_full_name = try refl.methodFullName(users_service, get_method);
    defer allocator.free(get_method_full_name);
    try std.testing.expectEqualStrings("demo.reflect.Users.Get", get_method_full_name);
    try std.testing.expect(try refl.methodInputType(users_service, get_method) == user_desc);
    try std.testing.expect(try refl.methodOutputType(users_service, get_method) == user_desc);
    try std.testing.expect(!refl.methodClientStreaming(get_method));
    try std.testing.expect(!refl.methodServerStreaming(get_method));
    try std.testing.expect(refl.optionBool(users_service.options.items, "deprecated").?);
    try std.testing.expectEqualStrings("NO_SIDE_EFFECTS", refl.optionValue(get_method.options.items, "idempotency_level").?.identifier);

    var user = try refl.newMessage("demo.reflect.User");
    defer user.deinit();

    try std.testing.expectEqual(@as(i32, 0), try refl.getInt32OrDefault(&user, "id"));
    try std.testing.expectEqualStrings("", try refl.getStringOrDefault(&user, "name"));
    try std.testing.expectEqual(@as(i32, 0), try refl.getEnumOrDefault(&user, "role"));
    try std.testing.expectEqualStrings("ROLE_UNKNOWN", (try refl.getEnumValueOrDefault(&user, "role")).name);
    try std.testing.expectEqualStrings("ROLE_UNKNOWN", (try refl.getEnumNameOrDefault(&user, "role")).?);

    try refl.setInt32(&user, "id", 7);
    try refl.setString(&user, "name", "Ada");
    try refl.addString(&user, "tags", "zig");
    try refl.addString(&user, "tags", "protobuf");
    try refl.putStringInt32MapEntry(&user, "counts", "red", 1);
    try refl.putStringInt32MapEntry(&user, "counts", "red", 2);
    try refl.setEnumByName(&user, "role", "ROLE_ADMIN");
    try std.testing.expectError(error.TypeMismatch, refl.setBytes(&user, "email", "ada@example.test"));
    try refl.setString(&user, "email", "ada@example.test");
    try refl.setUInt32(&user, "quota", 42);
    try refl.setUInt64(&user, "total", 9_000_000_000);
    try refl.setSInt32(&user, "delta", -12);
    try refl.setSInt64(&user, "big_delta", -9_000_000_000);
    try refl.setFixed32(&user, "checksum", 0xdead_beef);
    try refl.setFixed64(&user, "token", 0x0102_0304_0506_0708);
    try refl.setSFixed32(&user, "signed_fixed", -123);
    try refl.setSFixed64(&user, "signed_big_fixed", -456);
    try refl.setFloat(&user, "ratio", 1.5);
    try refl.setDouble(&user, "score", 9.25);
    try refl.addBool(&user, "flags", false);
    try refl.addBool(&user, "flags", true);
    try refl.addBytes(&user, "blobs", &.{ 1, 2 });
    try refl.addBytes(&user, "blobs", &.{ 3, 4 });
    try refl.addEnumByName(&user, "roles", "ROLE_UNKNOWN");
    try refl.addEnumByName(&user, "roles", "ROLE_ADMIN");
    try std.testing.expectError(error.UnknownEnum, refl.addEnumByName(&user, "roles", "ROLE_MISSING"));
    try refl.putMapEntryOwned(&user, "roles_by_key", .{ .string = try allocator.dupe(u8, "current") }, .{ .enumeration = 1 });
    try refl.addUInt32(&user, "samples", 10);
    try refl.addUInt32(&user, "samples", 20);
    try refl.addSInt64(&user, "deltas", -1);
    try refl.addSInt64(&user, "deltas", -2);
    try refl.addInt32(&user, "more_ids", 3);
    try refl.addInt64(&user, "more_totals", -4);
    try refl.addUInt64(&user, "more_unsigned", 5);
    try refl.addSInt32(&user, "more_deltas", -6);
    try refl.addFixed32(&user, "more_fixed32", 7);
    try refl.addFixed64(&user, "more_fixed64", 8);
    try refl.addSFixed32(&user, "more_sfixed32", -9);
    try refl.addSFixed64(&user, "more_sfixed64", -10);
    try refl.addFloat(&user, "more_floats", 1.25);
    try refl.addDouble(&user, "more_doubles", 2.5);

    const profile = try refl.mutableMessage(&user, "profile");
    try std.testing.expect(profile.descriptor == profile_desc);
    try std.testing.expect(profile == try refl.mutableMessage(&user, "profile"));
    try refl.setInt64(profile, "created_at", 123456);
    try refl.setBytes(profile, "avatar", &.{ 0xde, 0xad, 0xbe, 0xef });

    try std.testing.expect(try refl.hasField(&user, "id"));
    try std.testing.expectEqual(@as(i32, 7), try refl.getInt32(&user, "id"));
    try std.testing.expectEqualStrings("Ada", try refl.getString(&user, "name"));
    try std.testing.expectEqual(@as(usize, 2), try refl.repeatedLen(&user, "tags"));
    try std.testing.expectEqualStrings("protobuf", try refl.repeatedString(&user, "tags", 1));
    try std.testing.expect(try refl.setRepeatedValue(&user, "tags", 1, .{ .string = try allocator.dupe(u8, "pbz") }));
    try std.testing.expectEqualStrings("pbz", try refl.repeatedString(&user, "tags", 1));
    try std.testing.expectError(error.TypeMismatch, refl.repeatedInt32(&user, "tags", 1));
    try std.testing.expect(!try refl.setRepeatedValue(&user, "tags", 9, .{ .string = try allocator.dupe(u8, "missing") }));
    try std.testing.expectError(error.TypeMismatch, refl.setRepeatedValue(&user, "tags", 0, .{ .int32 = 1 }));
    try std.testing.expect(try refl.swapRepeatedValues(&user, "tags", 0, 1));
    try std.testing.expectEqualStrings("pbz", try refl.repeatedString(&user, "tags", 0));
    try std.testing.expect(!try refl.swapRepeatedValues(&user, "tags", 0, 5));
    try std.testing.expect(try refl.removeRepeatedValue(&user, "tags", 0));
    try std.testing.expectEqual(@as(usize, 1), try refl.repeatedLen(&user, "tags"));
    try std.testing.expectEqualStrings("zig", try refl.repeatedString(&user, "tags", 0));
    try std.testing.expectError(error.MissingField, refl.repeatedString(&user, "tags", 5));
    try std.testing.expect(!try refl.removeRepeatedValue(&user, "tags", 5));
    try std.testing.expectEqual(@as(i32, 1), try refl.getEnum(&user, "role"));
    try std.testing.expectEqual(@as(i32, 1), try refl.getEnumOrDefault(&user, "role"));
    try std.testing.expect(role_desc == try refl.enumForField(user_desc, try refl.fieldByName(user_desc, "role")));
    try std.testing.expectEqualStrings("ROLE_ADMIN", (try refl.getEnumValue(&user, "role")).name);
    try std.testing.expectEqualStrings("ROLE_ADMIN", (try refl.getEnumValueOrDefault(&user, "role")).name);
    try std.testing.expectEqual(@as(u32, 42), try refl.getUInt32(&user, "quota"));
    try std.testing.expectEqual(@as(u64, 9_000_000_000), try refl.getUInt64(&user, "total"));
    try std.testing.expectEqual(@as(i32, -12), try refl.getSInt32(&user, "delta"));
    try std.testing.expectEqual(@as(i64, -9_000_000_000), try refl.getSInt64(&user, "big_delta"));
    try std.testing.expectEqual(@as(u32, 0xdead_beef), try refl.getFixed32(&user, "checksum"));
    try std.testing.expectEqual(@as(u64, 0x0102_0304_0506_0708), try refl.getFixed64(&user, "token"));
    try std.testing.expectEqual(@as(i32, -123), try refl.getSFixed32(&user, "signed_fixed"));
    try std.testing.expectEqual(@as(i64, -456), try refl.getSFixed64(&user, "signed_big_fixed"));
    try std.testing.expectEqual(@as(f32, 1.5), try refl.getFloat(&user, "ratio"));
    try std.testing.expectEqual(@as(f64, 9.25), try refl.getDouble(&user, "score"));
    try std.testing.expect(try refl.getBool(&user, "flags"));
    try std.testing.expect(try refl.repeatedBool(&user, "flags", 1));
    try std.testing.expectEqualSlices(u8, &.{ 3, 4 }, try refl.repeatedBytes(&user, "blobs", 1));
    try std.testing.expectEqual(@as(i32, 1), try refl.repeatedEnum(&user, "roles", 1));
    const repeated_role_names = try refl.repeatedEnumNames(&user, "roles");
    defer allocator.free(repeated_role_names);
    try std.testing.expectEqual(@as(usize, 2), repeated_role_names.len);
    try std.testing.expectEqualStrings("ROLE_UNKNOWN", repeated_role_names[0]);
    try std.testing.expectEqualStrings("ROLE_ADMIN", repeated_role_names[1]);
    try std.testing.expectError(error.TypeMismatch, refl.repeatedEnumNames(&user, "name"));
    try std.testing.expectEqual(@as(u32, 20), try refl.repeatedUInt32(&user, "samples", 1));
    try std.testing.expectEqual(@as(i64, -2), try refl.repeatedSInt64(&user, "deltas", 1));
    try std.testing.expectEqual(@as(i32, 3), try refl.repeatedInt32(&user, "more_ids", 0));
    try std.testing.expectEqual(@as(i64, -4), try refl.repeatedInt64(&user, "more_totals", 0));
    try std.testing.expectEqual(@as(u64, 5), try refl.repeatedUInt64(&user, "more_unsigned", 0));
    try std.testing.expectEqual(@as(i32, -6), try refl.repeatedSInt32(&user, "more_deltas", 0));
    try std.testing.expectEqual(@as(u32, 7), try refl.repeatedFixed32(&user, "more_fixed32", 0));
    try std.testing.expectEqual(@as(u64, 8), try refl.repeatedFixed64(&user, "more_fixed64", 0));
    try std.testing.expectEqual(@as(i32, -9), try refl.repeatedSFixed32(&user, "more_sfixed32", 0));
    try std.testing.expectEqual(@as(i64, -10), try refl.repeatedSFixed64(&user, "more_sfixed64", 0));
    try std.testing.expectEqual(@as(f32, 1.25), try refl.repeatedFloat(&user, "more_floats", 0));
    try std.testing.expectEqual(@as(f64, 2.5), try refl.repeatedDouble(&user, "more_doubles", 0));
    try std.testing.expectEqualStrings("email", refl.whichOneof(&user, "contact").?.name);
    try std.testing.expectEqualStrings("ada@example.test", try refl.getString(&user, "email"));

    const count_field = (try refl.getField(&user, "counts")).?;
    try std.testing.expectEqual(@as(usize, 1), count_field.values.items.len);
    try std.testing.expectEqual(@as(i32, 2), count_field.values.items[0].map_entry.value.int32);
    try std.testing.expectEqual(@as(i32, 2), (try refl.stringMapValue(&user, "counts", "red")).?.int32);
    const red_lookup = try allocator.dupe(u8, "red");
    defer allocator.free(red_lookup);
    try std.testing.expectEqual(@as(i32, 2), (try refl.mapValue(&user, "counts", .{ .string = red_lookup })).?.int32);
    try std.testing.expect((try refl.stringMapEntry(&user, "counts", "missing")) == null);
    try std.testing.expectError(error.TypeMismatch, refl.mapValue(&user, "counts", .{ .int32 = 1 }));
    try std.testing.expectEqualStrings("ROLE_ADMIN", (try refl.stringMapEnumValueName(&user, "roles_by_key", "current")).?);
    const current_role_lookup = try allocator.dupe(u8, "current");
    defer allocator.free(current_role_lookup);
    try std.testing.expectEqualStrings("ROLE_ADMIN", (try refl.mapEnumValueName(&user, "roles_by_key", .{ .string = current_role_lookup })).?);
    try std.testing.expect((try refl.stringMapEnumValueName(&user, "roles_by_key", "missing")) == null);
    try std.testing.expectError(error.TypeMismatch, refl.stringMapEnumValueName(&user, "counts", "red"));
    try std.testing.expect(try refl.clearStringMapEntry(&user, "counts", "red"));
    try std.testing.expect((try refl.getField(&user, "counts")) == null);
    try refl.putStringInt32MapEntry(&user, "counts", "red", 2);

    const profile_value = try refl.getMessage(&user, "profile");
    try std.testing.expectEqual(@as(i64, 123456), try refl.getInt64(profile_value, "created_at"));
    try std.testing.expectEqualSlices(u8, &.{ 0xde, 0xad, 0xbe, 0xef }, try refl.getBytes(profile_value, "avatar"));

    var merge_target = try refl.cloneMessage(&user);
    defer merge_target.deinit();
    var patch = try refl.newMessage("demo.reflect.User");
    defer patch.deinit();
    try refl.setString(&patch, "name", "Grace");
    try refl.addString(&patch, "tags", "merged");
    try refl.setBool(&patch, "disabled", true);
    var patch_unknown = pbz.Writer.init(allocator);
    defer patch_unknown.deinit();
    try patch_unknown.writeUInt32(101, 7);
    try refl.appendUnknownRaw(&patch, patch_unknown.slice());
    try refl.mergeFrom(&merge_target, &patch);
    try std.testing.expectEqualStrings("Grace", try refl.getString(&merge_target, "name"));
    try std.testing.expectEqual(@as(usize, 2), try refl.repeatedLen(&merge_target, "tags"));
    try std.testing.expectEqualStrings("merged", (try refl.repeatedValue(&merge_target, "tags", 1)).string);
    try std.testing.expectEqualStrings("disabled", refl.whichOneof(&merge_target, "contact").?.name);
    try std.testing.expect(refl.hasUnknownFieldNumber(&merge_target, 101));
    try refl.mergeFrom(&merge_target, &merge_target);
    try std.testing.expectEqual(@as(usize, 4), try refl.repeatedLen(&merge_target, "tags"));

    var copied = try refl.newMessage("demo.reflect.User");
    defer copied.deinit();
    try refl.setInt32(&copied, "id", 999);
    try refl.copyFrom(&copied, &user);
    try std.testing.expectEqualStrings("Ada", try refl.getString(&copied, "name"));
    try std.testing.expectEqual(@as(i32, 7), try refl.getInt32(&copied, "id"));
    try refl.copyFrom(&copied, &copied);
    try std.testing.expectEqualStrings("Ada", try refl.getString(&copied, "name"));
    var cloned = try refl.cloneMessage(&copied);
    defer cloned.deinit();
    try refl.setString(&copied, "name", "mutated");
    try std.testing.expectEqualStrings("Ada", try refl.getString(&cloned, "name"));
    try std.testing.expectError(error.TypeMismatch, refl.mergeFrom(&copied, profile_value));

    const encoded = try user.encodedInitializedWithRegistry(app_file, &loaded.registry);
    defer allocator.free(encoded);
    var decoded = pbz.DynamicMessage.init(allocator, user_desc);
    defer decoded.deinit();
    try decoded.decodeInitializedWithRegistry(app_file, &loaded.registry, encoded);
    try std.testing.expectEqual(@as(i32, 7), try refl.getInt32(&decoded, "id"));
    try std.testing.expectEqualStrings("email", refl.whichOneof(&decoded, "contact").?.name);
    try std.testing.expectEqualStrings("ada@example.test", try refl.getString(&decoded, "email"));

    var raw_unknown = pbz.Writer.init(allocator);
    defer raw_unknown.deinit();
    try raw_unknown.writeUInt32(100, 1);
    try refl.appendUnknownRaw(&decoded, raw_unknown.slice());
    try std.testing.expectEqual(@as(usize, 1), refl.unknownCount(&decoded));
    try std.testing.expect(refl.hasUnknownFieldNumber(&decoded, 100));
    try std.testing.expectEqual(@as(usize, 1), refl.unknownFieldCountByNumber(&decoded, 100));
    const unknown_numbers = try refl.unknownFieldNumbers(&decoded);
    defer allocator.free(unknown_numbers);
    try std.testing.expectEqualSlices(pbz.FieldNumber, &.{100}, unknown_numbers);
    const unknown_runs = try refl.unknownFieldNumberRuns(&decoded);
    defer allocator.free(unknown_runs);
    try std.testing.expectEqual(@as(usize, 1), unknown_runs.len);
    try std.testing.expectEqual(@as(pbz.FieldNumber, 100), unknown_runs[0].number);
    try std.testing.expectEqual(@as(usize, 1), unknown_runs[0].count);
    try std.testing.expectEqualSlices(u8, raw_unknown.slice(), refl.unknownByNumber(&decoded, 100)[0].data);
    const owned_unknown = try refl.unknownByNumberAlloc(&decoded, 100);
    defer allocator.free(owned_unknown);
    try std.testing.expectEqual(@as(usize, 1), owned_unknown.len);
    refl.clearUnknownFieldsByNumber(&decoded, 100);
    try std.testing.expectEqual(@as(usize, 0), refl.unknownCount(&decoded));
    try refl.appendUnknownRaw(&decoded, raw_unknown.slice());
    refl.clearUnknownFields(&decoded);
    try std.testing.expectEqual(@as(usize, 0), refl.unknownFields(&decoded).len);

    const json = try pbz.stringifyJsonAllocWithRegistry(allocator, app_file, &loaded.registry, &user, .{});
    defer allocator.free(json);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"profile\":") != null);
    var from_json = try pbz.parseJsonAllocWithRegistry(allocator, app_file, &loaded.registry, user_desc, json, .{});
    defer from_json.deinit();
    try std.testing.expectEqual(@as(i32, 7), try refl.getInt32(&from_json, "id"));
    try std.testing.expectEqual(@as(i64, 123456), try refl.getInt64(from_json.get("profile").?.values.items[0].message, "created_at"));

    try refl.setBool(&user, "disabled", true);
    try std.testing.expect(try refl.hasOneof(&user, "contact"));
    try std.testing.expectEqualStrings("disabled", refl.whichOneof(&user, "contact").?.name);
    try std.testing.expect(try refl.getBool(&user, "disabled"));
    try std.testing.expectEqualStrings("contact", (try refl.oneofByName(user_desc, "contact")).name);
    try std.testing.expectEqualStrings("contact", refl.oneofName(try refl.oneofByName(user_desc, "contact")));
    const contact_full_name = try refl.oneofFullName(user_desc, try refl.oneofByName(user_desc, "contact"));
    defer allocator.free(contact_full_name);
    try std.testing.expectEqualStrings("demo.reflect.User.contact", contact_full_name);
    const contact_fields = try refl.oneofFields(user_desc, "contact");
    defer allocator.free(contact_fields);
    try std.testing.expectEqual(@as(usize, 2), contact_fields.len);
    try std.testing.expectEqualStrings("email", contact_fields[0].name);
    try std.testing.expectEqualStrings("disabled", contact_fields[1].name);
    try std.testing.expect(try refl.clearOneof(&user, "contact"));
    try std.testing.expect(!(try refl.hasOneof(&user, "contact")));
    try std.testing.expect(refl.whichOneof(&user, "contact") == null);
    try std.testing.expectError(error.MissingField, refl.getBool(&user, "disabled"));
    try refl.setBool(&user, "disabled", true);

    try refl.clearField(&user, "name");
    try std.testing.expect(!(try refl.hasField(&user, "name")));
    try std.testing.expectError(error.MissingField, refl.getString(&user, "name"));

    var required_file = try pbz.ProtoParser.parse(allocator,
        \\syntax = "proto2";
        \\package demo.required_reflect;
        \\message Child { required int32 id = 1; }
        \\message Parent {
        \\  required string name = 1;
        \\  optional Child child = 2;
        \\  optional int32 priority = 3 [default = 7];
        \\  optional group Legacy = 4 { optional int32 code = 5; }
        \\  repeated Child children = 6;
        \\  repeated group Item = 7 { optional int32 code = 8; }
        \\}
    );
    defer required_file.deinit();
    required_file.name = "required-reflect.proto";
    var required_registry = pbz.Registry.init(allocator);
    defer required_registry.deinit();
    try required_registry.addFile(&required_file);

    const required_refl = pbz.Reflection.init(allocator, &required_registry);
    var parent = try required_refl.newMessage(".demo.required_reflect.Parent");
    defer parent.deinit();
    const priority_field = try required_refl.fieldByName(parent.descriptor, "priority");
    try std.testing.expect(required_refl.fieldHasDefaultValue(priority_field));
    try std.testing.expectEqual(@as(i64, 7), (try required_refl.fieldExplicitDefaultValue(priority_field)).integer);
    try std.testing.expectEqual(@as(i32, 7), (try required_refl.getFieldOrDefault(&parent, "priority")).int32);
    const required_child_field = try required_refl.fieldByName(parent.descriptor, "child");
    try std.testing.expectEqualStrings("Child", try required_refl.fieldTypeName(required_child_field));
    const child_desc = try required_refl.message(".demo.required_reflect.Child");
    try std.testing.expect(child_desc == try required_refl.fieldMessageType(parent.descriptor, required_child_field));
    const legacy_field = try required_refl.fieldByName(parent.descriptor, "legacy");
    try std.testing.expectEqualStrings("Legacy", try required_refl.fieldTypeName(legacy_field));
    const legacy_desc = try required_refl.fieldGroupType(parent.descriptor, legacy_field);
    try std.testing.expectEqualStrings("Legacy", legacy_desc.name);
    const legacy_full_name = try required_refl.messageFullName(legacy_desc);
    defer allocator.free(legacy_full_name);
    try std.testing.expectEqualStrings("demo.required_reflect.Parent.Legacy", legacy_full_name);
    const required_name_field = try required_refl.fieldByName(parent.descriptor, "name");
    try std.testing.expect(!required_refl.fieldHasDefaultValue(required_name_field));
    try std.testing.expectError(error.MissingField, required_refl.fieldExplicitDefaultValue(required_name_field));
    try std.testing.expect(!required_refl.isInitialized(&parent));
    try std.testing.expectError(error.MissingRequiredField, required_refl.validateInitialized(&parent));
    const missing_name = (try required_refl.missingRequiredFieldPath(&parent)).?;
    defer allocator.free(missing_name);
    try std.testing.expectEqualStrings("name", missing_name);

    try required_refl.setString(&parent, "name", "root");
    const child = try required_refl.mutableMessage(&parent, "child");
    try std.testing.expect(child.descriptor == child_desc);
    const appended_child = try required_refl.addMutableMessage(&parent, "children");
    try std.testing.expect(appended_child.descriptor == child_desc);
    try required_refl.setInt32(appended_child, "id", 2);
    try std.testing.expectEqual(@as(usize, 1), try required_refl.repeatedLen(&parent, "children"));
    try std.testing.expect((try required_refl.repeatedMessage(&parent, "children", 0)) == appended_child);
    try std.testing.expect((try required_refl.mutableRepeatedMessage(&parent, "children", 0)) == appended_child);
    try std.testing.expectEqual(@as(i32, 2), try required_refl.getInt32(try required_refl.repeatedMessage(&parent, "children", 0), "id"));
    try std.testing.expectError(error.TypeMismatch, required_refl.repeatedMessage(&parent, "item", 0));
    try std.testing.expectError(error.MissingField, required_refl.repeatedMessage(&parent, "children", 9));
    try std.testing.expectError(error.TypeMismatch, required_refl.addMutableMessage(&parent, "child"));
    const appended_group = try required_refl.addMutableGroup(&parent, "item");
    try std.testing.expect(appended_group.descriptor == try required_refl.fieldGroupType(parent.descriptor, try required_refl.fieldByName(parent.descriptor, "item")));
    try required_refl.setInt32(appended_group, "code", 9);
    try std.testing.expect((try required_refl.repeatedGroup(&parent, "item", 0)) == appended_group);
    try std.testing.expect((try required_refl.mutableRepeatedGroup(&parent, "item", 0)) == appended_group);
    try std.testing.expectEqual(@as(i32, 9), try required_refl.getInt32(try required_refl.repeatedGroup(&parent, "item", 0), "code"));
    try std.testing.expectError(error.TypeMismatch, required_refl.repeatedGroup(&parent, "children", 0));
    try std.testing.expectError(error.MissingField, required_refl.repeatedGroup(&parent, "item", 9));
    try std.testing.expectError(error.TypeMismatch, required_refl.addMutableGroup(&parent, "child"));
    const missing_child = (try required_refl.missingRequiredFieldPath(&parent)).?;
    defer allocator.free(missing_child);
    try std.testing.expectEqualStrings("child.id", missing_child);

    try required_refl.setInt32(try required_refl.getMessage(&parent, "child"), "id", 1);
    try required_refl.validateInitialized(&parent);
    try std.testing.expect(required_refl.isInitialized(&parent));
    try std.testing.expect((try required_refl.missingRequiredFieldPath(&parent)) == null);
}

comptime {
    _ = pbz;
}
